name: CMake Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Install Other Dependencies
      run: |
          sudo apt-get remove --purge man-db # Disable man pages to speed up installation
          sudo apt-get update
          sudo apt-get install -y cmake gcovr

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test and Coverage
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target coverage

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        args: >
          -Dsonar.organization=mocelik
          -Dsonar.projectKey=mocelik_protobuf-cpp
          -Dsonar.sources=src,include
          -Dsonar.tests=test
          -Dsonar.cfamily.compile-commands=build/compile_commands.json
          -Dsonar.coverageReportPaths=build/coverage.xml
          -Dsonar.coverage.exclusions=test/**/*
